---

- import_playbook: dns-record-update.yml

- hosts: localhost
  vars_files:
    - "./vars/{{ env_type }}.yml" 
  tasks:
  - name: Delete Heat stack from generated template
    command: openstack stack delete  --os-cloud {{ guid }}-project {{ env_type }}-stack-{{ guid }}
